# Generated by Django 5.0.1 on 2024-01-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tag_alter_task_title_alter_task_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tags',
            new_name='tag',
        ),
    ]
